/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package denme;
import static spark.Spark.get;
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        get("/compute", (req, res) -> "Hello World");
    }
}
